http_port 3128
acl localnet src 10.200.0.0/24
http_access allow localnet
http_access deny all
acl blocked_domains dstdomain blocked_domains.txt
http_access deny blocked_domains
acl blocked_extensions urlpath_regex -i \.(exe|bat|ps1|msi|scr)$
http_access deny blocked_extensions
