http_port 3128
acl localnet src 10.200.0.0/24
http_access allow localnet
http_access deny all

acl blocked_domains dstdomain blocked_domains.txt
http_access deny blocked_domains

acl blocked_extensions urlpath_regex -i \.(exe|bat|ps1|msi|scr)$
http_access deny blocked_extensions

https_port 3129 intercept ssl-bump cert=/etc/squid/ssl_cert/myCA.pem

acl step1 at_step SslBump1
ssl_bump peek step1
ssl_bump splice all

logformat detailed [%{%Y-%m-%d %H:%M:%S}tl] %tr %a %Ss/%03Hs %<st %rm %ru %[un %Sh/%<a %mt
access_log daemon:/var/log/squid/access.log detailed

