#!/bin/bash
# Central configuration. Environment variables always take precedence.
: "${VPN_INTERFACE:=wg0}"
: "${VPN_SUBNET:=10.8.0.0/24}"
: "${VPN_SERVER_IP:=10.8.0.1/24}"
: "${VPN_SERVER_ADDRESS:=${VPN_SERVER_IP%/*}}"
: "${IT_VPN_IP:=10.8.0.10}"
: "${FINANCE_VPN_IP:=10.8.0.20}"
: "${DATABASE_VPN_IP:=10.8.0.30}"
: "${VPN_PORT:=51820}"
: "${SSH_PORT:=22}"
: "${FTP_CONTROL_PORT:=21}"
: "${FTP_PASSIVE_MIN:=50000}"
: "${FTP_PASSIVE_MAX:=50100}"
: "${DATABASE_PORT:=3306}"
: "${PANIC_DELAY:=5}"

: "${BACKDOOR_CRON:=/etc/cron.d/logicorp}"
: "${UNNECESSARY_SERVICES:=ttyd openvscode-server}"
: "${SSHD_CONFIG:=/etc/ssh/sshd_config}"
: "${VSFTPD_CONFIG:=/etc/vsftpd.conf}"
: "${STARTUP_SCRIPT:=/etc/run.sh}"
: "${NFTABLES_CONFIG:=/etc/nftables.conf}"
: "${NFT_BIN:=/usr/sbin/nft}"
: "${PANIC_JOB_FILE:=/run/logicorp-panic.job}"
: "${WIREGUARD_DIR:=/etc/wireguard}"
: "${WG_CONFIG:=$WIREGUARD_DIR/$VPN_INTERFACE.conf}"
: "${WG_PRIVATE_KEY:=$WIREGUARD_DIR/server_private.key}"
: "${WG_PUBLIC_KEY:=$WIREGUARD_DIR/server_public.key}"
: "${WG_CLIENT_TEMPLATE:=$WIREGUARD_DIR/client_template.conf}"
: "${SYSCTL_FORWARD_CONFIG:=/etc/sysctl.d/90-wireguard-forwarding.conf}"
: "${FTPS_CERT:=/etc/ssl/certs/logicorp-ftps.crt}"
: "${FTPS_KEY:=/etc/ssl/private/logicorp-ftps.key}"
: "${FTPS_CERT_DAYS:=825}"
: "${FTPS_CERT_SUBJECT:=/CN=logicorp-ftps}"
